project:
  type: website
  output-dir: docs

website:
  title: "DSPG 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: allBlogs.qmd
        text: Blogs
      - about.qmd
      

format:
  html:
    theme: [simplex, theme-simplex.scss]
    css: styles.css
    toc: true

editor: visual

