project:
  type: website
  output-dir: docs

website:
  title: "DSPG2023_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - allBlogs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

